name: .NET Desktop CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      SOLUTION: '**/*.sln'
      DD_TRACE_DEBUG: 1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Propagate service name and API key from inputs to environment variables
        run: |
          echo "DD_SERVICE print-this" | awk '{print $2}'
        shell: bash

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Restore NuGet packages
        run: nuget restore $SOLUTION

      - name: Build solution
        run: |
          msbuild $SOLUTION /p:Platform="Any CPU" /p:Configuration=Release

      - name: Install .NET 6 SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.x

      - name: Configure Datadog Test Visibility
        uses: nikita-tkachenko-datadog/gha-composite-test@v36
        with:
          languages: dotnet
          service-name: ci-test-project-gha
          api-key: ${{ secrets.DD_API_KEY }}

      - name: Run tests
        uses: microsoft/vstest-action@main
        with:
          testAssembly: '**\*MsTest.dll'
          platform: 'Any CPU'

      - name: Publish Logs
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: 'C:\ProgramData\Datadog .NET Tracer\logs'
